name: 'Cache de Dependências Node e NPM'
description: 'Esta ação permite fazer cache das dependências do Node e NPM com base no arquivo package-lock.json.'

inputs:
  node-version:
    description: 'Versão do NodeJS a ser utilizada'
    required: true
    default: '20.x'
  working-dir:
    description: 'O diretório de trabalho da aplicação'
    required: false
    default: '.'
  target-env:
    description: '"dev" ou "prod". Controla se as dependências de desenvolvimento são instaladas.'
    required: false
    default: 'dev'

runs:
  using: "composite"
  steps:
    - name: Configurando a versão ${{ inputs.node-version }} do NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Fazer cache das dependências
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: ${{ runner.os }}-npm-${{ inputs.target-env }}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ inputs.target-env }}-

    - name: Instalar dependências de desenvolvimento
      if: steps.cache.outputs.cache-hit != 'true' && inputs.target-env == 'dev'
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: npm ci

    - name: Instalar dependências de produção
      if: steps.cache.outputs.cache-hit != 'true' && inputs.target-env == 'prod'
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: npm ci --omit=dev
