name: 01 - Building Blocks

on:
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
        
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Passed step
        run: |
          echo "This will now work correctly."
          echo "The syntax is fixed."
      - name: Say goodbye
        run: echo "Goodbye!"