name: 03 - Workflow Runners
on:
  push:
  workflow_dispatch:
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          "This job is running on an Ubuntu runner."
          uname -a
  windows-echo:
    runs-on: windows-latest
    steps:
        - name: Show OS
          run: |
            "This job is running on a Windows runner."
            systeminfo | findstr /B /C:"OS Name" /C:"
  max-echo:
    runs-on: macos-latest
    steps:
        - name: Show OS
          run: |
            "This job is running on a macOS runner."
            sw_vers