name: 05 - 2 - Event Filters and Activity Types
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: Mostrar mensagem quando PR for fechado
          run: echo "Executando sempre que um PR for fechado E a branch base for main"
