name: 12 - Working with Outputs (Mistake Demo)
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        description: 'Simulated status of the build'
        default: 'success'
        options:
          - success
          - failure
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # Exportando 'build-status' e 'output1' do job
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
    steps:
      - name: Build
        id: build
        run: |
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
          echo "output1=value1" >> $GITHUB_OUTPUT
          echo "--- Conteúdo ANTES do erro ---"
          cat $GITHUB_OUTPUT
          echo "mistake=true" > $GITHUB_OUTPUT
          echo "--- Conteúdo DEPOIS do erro (Erro tirado nesse novo commit) ---"
          cat $GITHUB_OUTPUT
          echo "output2=value2" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.build-status == 'success'
    steps:
      - name: Print Outputs
        run: |
          echo "Deploying..."
          echo "Output 1 from build job is: ---${{ needs.build.outputs.output1 }}---"