name: 14 - Working with Artifacts
on:
  workflow_dispatch: {}
env:
  build-artifact-key: app-${{ github.sha }}
  test-coverage-key: test-coverage-${{ github.sha }}

jobs:
  # JOB 1: Testa o código, gera o build e os relatórios, e "envia" os resultados como artefatos.
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: 14-artifacts/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Unit tests
        # A flag '-- --coverage' diz ao 'npm test' para gerar um relatório de cobertura de testes.
        # Isso cria a pasta 'coverage' que faremos upload.
        run: npm run test -- --coverage

      - name: Upload test results
        # "Empacota" a pasta 'coverage' e a envia para o armazenamento do GitHub.
        uses: actions/upload-artifact@v4
        with:
          # O nome do pacote (artefato)
          name: ${{ env.test-coverage-key }}
          # O que vai dentro do pacote
          path: 14-artifacts/react-app/coverage

      - name: Build code
        run: npm run build

      - name: Upload build files
        # "Empacota" a pasta 'build' (o app compilado) e a envia.
        uses: actions/upload-artifact@v4
        with:
          # O nome do pacote (artefato)
          name: ${{ env.build-artifact-key }}
          # O que vai dentro do pacote
          path: 14-artifacts/react-app/build

  # JOB 2: Recebe os arquivos do build e simula um deploy.
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build files
        # Pede ao GitHub para baixar o pacote com o nome correspondente.
        uses: actions/download-artifact@v4
        with:
          # O nome do pacote a ser baixado
          name: ${{ env.build-artifact-key }}
          # Onde desempacotar os arquivos. Neste caso, uma pasta 'build' na raiz.
          path: build

      - name: Show folder structure
        # Este comando prova que os arquivos foram baixados corretamente.
        run: ls -R