name: 15 - Working with Matrices
on:
  workflow_dispatch: {}
jobs:
  backwards-compatibility:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 16.x
            os: ubuntu-latest
          - node-version: 21.x
            os: ubuntu-latest
            tag: experimental
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: |
          echo "This is the experimental build, and it will fail on purpose."
          exit 1
          # Se retirarmos esse exit 1, o job passará normalmente.
      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
          sleep 10
      - name: Upload test results
        run: echo "Uploading test results"